version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file: ".env"
    restart: "always"
    ports:
      - "8082:8082"
    depends_on:
      - db
    command: >
      sh -c "
        go run ./cmd/migrator --migrations-path=./migrations
      "
  db:
    image: postgres:16
    env_file: ".env"
    restart: "always"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"